name: Mineopoly
main: com.kill3rtaco.mineopoly.Mineopoly
version: 1.4
description: Monopoly port for Bukkit servers
author: KILL3RTACO
depend: [TacoAPI, WorldEdit]
commands:
  mineopoly:
    description: Mineopoly player commands
    aliases: [m, mgame]
  property:
    description: Mineopoly property commands
    aliases: [mproperty, mprop, prop, p]
  jail:
    description: Mineopoly jail commands
    aliases: [j, mjail]
